const RouteNames = {
    Splash: 'SplashScreen',
    onBoarding: 'OnboardingScreen',
    Login: 'LoginScreen',
    Register: 'RegisterScreen',
    Forgot: 'ForgotScreen',
    OtpVerify: 'OtpVerifyScreen',
    LanguageSet: 'LanguageSetScreen',
    BottomTab: 'BottomTab',
    Home: 'HomeScreen',
    Search: 'SearchScreen',
    RestaurentDetails: 'RestaurentDetails',
    FoodDetail: 'FoodDetailScreen',
    Cart: 'CartScreen',
    CheckOut: 'CheckOutScreen',
    Orders: 'OrdersScreen',
    OrderDetails: 'OrderDetails',
    Profile: 'ProfileScreen',
    Notifications: 'NotificationsScreen',
    HowToUse: 'HowToUseScreen',
    HelpScreen: 'HelpScreen',
    EditProfile: 'EditProfile',
    AddressList: 'AddressList',
    EditAddress: 'EditAddress',
    OrderSuccessful: 'OrderSuccessful',
    PaymentCard: 'PaymentCard',
}

export default RouteNames;