import SplashScreen from "./Splash";
import OnboardingScreen from "./Onboarding";
import LoginScreen from "./auth/Login";
import RegisterScreen from "./auth/Register";
import ForgotScreen from "./auth/Forgot";
import OtpVerifyScreen from "./auth/OtpVerify";
import LanguageSetScreen from "./Language";
import HomeScreen from "./Home";
import SearchScreen from "./Search";
import RestaurentDetails from "./RestaurantDetails";
import FoodDetailScreen from "./FoodDetails";
import CartScreen from "./Cart";
import CheckOutScreen from "./CheckOut";
import OrdersScreen from "./Orders";
import OrderDetails from "./OrderDetails";
import ProfileScreen from "./Profile";
import NotificationsScreen from "./Notifications";
import HowToUseScreen from "./HowToUse";
import HelpScreen from "./Help";
import EditProfile from "./EditProfile";
import AddressList from "./AddressList";
import EditAddress from "./EditAddress";
import OrderSuccessful from "./OrderSuccessful";
import PaymentCard from "./PaymentCard";

export { SplashScreen, OnboardingScreen, LoginScreen, RegisterScreen, ForgotScreen, OtpVerifyScreen, LanguageSetScreen, HomeScreen, SearchScreen, RestaurentDetails, FoodDetailScreen, CartScreen, CheckOutScreen, OrdersScreen, OrderDetails, ProfileScreen, NotificationsScreen, HowToUseScreen, HelpScreen, EditProfile, AddressList, EditAddress, OrderSuccessful, PaymentCard };